// ── Airtable Snapshot — Table Clients (appUxa9p0fQwPhQOd / tblOsQdltpPG8Jxcd)
// Exported: 2026-02-26

const clients = [
  {
    nom: 'Dupont Fiduciaire',
    contact: 'Marie Dupont',
    email: 'marie@dupont-fiduciaire.lu',
    priorite: 'haute',
    caAnnuel: 48000,
    joursRetard: 0,
    relancesEnvoyees: 0,
    cycleFact: 'mensuel',
    conditionsPaiement: '30 jours',
  },
  {
    nom: 'Keysource Management',
    contact: 'Philippe Renard',
    email: 'p.renard@keysource.lu',
    priorite: 'haute',
    caAnnuel: 72000,
    joursRetard: 45,
    relancesEnvoyees: 3,
    cycleFact: 'mensuel',
    conditionsPaiement: '30 jours',
  },
  {
    nom: 'Patrimonia Family Office',
    contact: 'Isabelle Fontaine',
    email: 'i.fontaine@patrimonia.lu',
    priorite: 'moyenne',
    caAnnuel: 36000,
    joursRetard: 8,
    relancesEnvoyees: 1,
    cycleFact: 'trimestriel',
    conditionsPaiement: '45 jours',
  },
  {
    nom: 'BGL Advisory',
    contact: 'Thomas Weber',
    email: 't.weber@bgl-advisory.lu',
    priorite: 'haute',
    caAnnuel: 96000,
    joursRetard: 22,
    relancesEnvoyees: 2,
    cycleFact: 'mensuel',
    conditionsPaiement: '30 jours',
  },
  {
    nom: 'Nordea Fund Services',
    contact: 'Anna Lindqvist',
    email: 'a.lindqvist@nordea-fs.lu',
    priorite: 'moyenne',
    caAnnuel: 24000,
    joursRetard: 0,
    relancesEnvoyees: 0,
    cycleFact: 'trimestriel',
    conditionsPaiement: '60 jours',
  },
  {
    nom: 'Comptaflex',
    contact: 'Jean-Marc Hoffmann',
    email: 'jm.hoffmann@comptaflex.lu',
    priorite: 'basse',
    caAnnuel: 18000,
    joursRetard: '12',
    relancesEnvoyees: 1,
    cycleFact: 'mensuel',
    conditionsPaiement: '30 jours',
  },
  {
    nom: 'Ardian Luxembourg',
    contact: 'Sophie Muller',
    email: 's.muller@ardian.lu',
    priorite: 'haute',
    caAnnuel: 120000,
    joursRetard: 60,
    relancesEnvoyees: 5,
    cycleFact: 'mensuel',
    conditionsPaiement: '15 jours',
  },
];

module.exports = clients;
